### PR TITLE
Add possibility to get query_id from outside

### PR DESCRIPTION
**Pull request by AntonKuzValid**
I need possibility to save query_id, wchich i have added on my side. But proxy changes to another. Add possibility to get from the parametres of incoming request

### CODE REVIEW

**Review by valyala — COMMENTED** [review]
I'm unsure this PR is safe to use, since the generated `query_id` is used for query logging and cancellation. This means all the queries must have distinct `query_id` values. It is unclear how to ensure this when using the `query_id` provided by the client.

**Comment by AntonKuzValid** [comment]
Probably the solution is to give to clients an opportunity to decide what query_id to use (their own or proxy generated). I'm sure there could be cases when it's really needed, for example for query audit I save user_id of my service and query_id, and firstly it was unclear why I can't find my query_ids in click house

**Comment by hagen1778** [comment]
What if proxy will send generated query_id back in response headers?

**Comment by mga-chka** [comment]
I'm closing this PR since it's been stale for a lot of time.
Feel free to reopen it if needed

**Pull request closed without merging**
