### PR TITLE
Hide redis sensitive info

### PR DESCRIPTION
**Pull request by ven-shupo**
## Description
https://github.com/ContentSquare/chproxy/issues/281

## Pull request type
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Checklist

- [x] Linter passes correctly
- [x] Add tests which fail without the change (if possible)
- [x] All tests passing
- [x] Extended the README / documentation, if necessary

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ven-shupo** [comment]
@ilejn, hello! Can you please run CI?

**Comment by ilejn** [comment]
> @ilejn, hello! Can you please run CI?

Not sure that I understand what you mean.
Should I create a fake commit in PR 275 to trigger CI?

**Comment by ven-shupo** [comment]
> > @ilejn, hello! Can you please run CI?
> 
> Not sure that I understand what you mean. Should I create a fake commit in PR 275 to trigger CI?

Sorry, i should have tagged the maintainer to run CI, but apparently i missed
https://github.com/ContentSquare/chproxy/blob/master/CONTRIBUTING.md#contributing-code

Maybe @sigua-cs can help me?

**Comment by ilejn** [comment]
> i should have tagged the maintainer to run CI

@ven-shupo, your mistake is more or less obvious. What puzzled me is that @mga-chka liked your comment ;)
Good luck with your PR!

**Comment by mga-chka** [comment]
my +1 was a fast way to say "I'll run the CI", I didn't find a better emoticon

**Review by mga-chka — APPROVED** [review]
FYI since most of us are off, the next release will (that will contains your PR) will be released in January. I don't merge it yet so that other maintainers can review it if they want

**Pull request merged**
