### PR TITLE
Session_timeout bug fix & Local Build Process fixup

### PR DESCRIPTION
**Pull request by pavelnemirovsky**
- Bump to newer go
- Dependencies fix 

In continue of https://github.com/Vertamedia/chproxy/pull/117

### CODE REVIEW

**Review by vfoucault — COMMENTED** [review]
I believe it would be better to switch to goreleaser with github actions. It would save the hassle to deal with local file, and would ease the release process for new tags.

Could you also squash your commits. Thx

**Comment by pavelnemirovsky** [comment]
@vfoucault yes, that's exactly what I proposed in my original PR since there is no automatic versioning and artifact building. Let's do it, Let's squash once it will be merged into master.

**Comment by gontarzpawel** [comment]
Hello @pavelnemirovsky , github actions are now available in chproxy. Could you rebase your PR so we can leverage the fix you'd submitted for session timeout?

**Comment by mga-chka** [comment]
I'm closing this PR since it has been stale for too long. Feel free to re open it if you want to finish it.

**Pull request closed without merging**
