### PR TITLE
Support ping endpoint

### PR DESCRIPTION
**Pull request by hulk8**
## Description

It's similar with #127 issue.

chproxy returns HTTP 200 response for `/ping` endpoint and not proxying this request.
I want to add `/ping` endpoint to proxy, because some of BI instruments use this endpoint by default for healthchecks.

### Feature
- [x] added support for proxying `/ping` endpoint.
- [x] added option `allow_ping` to config on global scope for enabling `ping` endpoint proxying.

## Does this introduce a breaking change?
-  No

## Further comments
I've created config option on global scope in first version. If you think that it's necessary to create it on `network_groups` or `server` section (to allow ping endpoint only from some networks), then I can do that.

### CODE REVIEW

**Comment by mga-chka** [comment]
FYI, we're already handling the /ping, so there must be a recent issue, cf [this PR](https://github.com/ContentSquare/chproxy/pull/214). So if there is an issue, it's better to fix the heartbeat logic than creating a new ping logic.

**Comment by hulk8** [comment]
@mga-chka 
It's different from heartbeat logic.

As I understand, chproxy can create heartbeats to ClickHouse cluster. Heartbeat config can be configured for `/ping` endpoint in ClickHouse nodes (configured via section `clusters/heartbeat`).
Something like this:
```
...
clusters:
  - name: "dl"
    scheme: "http"
    nodes: ["click1:8123"]
    heartbeat:
      interval: 15s
      timeout: 10s
      request: "/ping"
      response: "Ok.\n"
...
```

But on chproxy level I can't create `/ping` request to proxy as if it was ClickHouse node. This is what I'm trying to add in this PR and It seems to me what in issue #127 was requested (in [this comment](https://github.com/ContentSquare/chproxy/issues/127#issuecomment-2268405145) for example).
When I'm trying to send ping request I have this exception:
```sh
> curl --request GET --url http://some_chproxy:8123/ping                                                                                                                                              
"172.23.0.1:54784": unsupported path: "/ping"
```

We faced this problem while integrating some BI instruments to chproxy which use `/ping` endpoint for self connection healthcheck. These changes helped solve this problem in our cases.

**Comment by mga-chka** [comment]
my bad, you're right.
can you check the golangci-lint issue?

**Comment by mga-chka** [comment]
Can you add tests (in main_test.go) to ensure the /ping works when it's put on and doesn't work when it's off.
You also need to remove you debug.yml since no one will understand the meaning of this conf and it's not used.

**Comment by hulk8** [comment]
Ok, I will add tests and remove debug.yml.

**Comment by hulk8** [comment]
@mga-chka, hi!

I've:
- [x] added two tests:
    - [x] `http ping request` - http `/ping` request without auth args mapped to default user in config.
   - [x] `https ping request` - https `/ping` request with auth args provided.
- [x] removed `debug.yml` from examples.
- [x] done some refactoring to minimize changes to the source code.

All tests are passed.

**Comment by mga-chka** [comment]
great, the linter is still not happy, cf the [last build](https://github.com/ContentSquare/chproxy/actions/runs/10673571068/job/29652284014?pr=456)
```Error: string `/ping` has 4 occurrences, make it a constant (goconst)```
Can you also add one test when the ping is not activated (for example by taking the conf testdata/http.yml)?

**Comment by hulk8** [comment]
@mga-chka I've:
- [x] created `pingEndpoint` constant for linter.
- [x] added test for disabled ping by default (conf `testdata/http.yml`).

**Review by mga-chka — APPROVED** [review]
looks good to me. I'm waiting a few days before merging in case another reviewer wants to look at the PR

**Pull request merged**
