### PR TITLE
add log_comment to allowedParams

### PR DESCRIPTION
**Pull request by profick**
## Description

https://github.com/ContentSquare/chproxy/issues/431

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Checklist

- [ ] Linter passes correctly
- [x] Add tests which fail without the change (if possible)
- [x] All tests passing
- [x] Extended the README / documentation, if necessary

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by mga-chka — APPROVED** [review]
LGTM, I'll let a bit of time to the other maintainers to review it

**Comment by profick** [comment]
@mga-chka Hello! 
Can you tell me does `go-test / build (pull_request)` pipeline step failure blocks PR? 
And what is an estimate time when we can merge this?

**Comment by mga-chka** [comment]
the failure is due to a bug in our CI pipeline (the generation of the code coverage, which is the last step, often fails). So it's not linked to your PR.
I'll merge the PR now. FYI, we're quite busy so we won't release a new version before June

**Comment by profick** [comment]
>I'll merge the PR now. FYI, we're quite busy so we won't release a new version before June

Ok, it's fine for me. Thank you!

**Pull request merged**
