### PR TITLE
limits: allow block user by negative rate limit

### PR DESCRIPTION
**Pull request by tomershafir**
## Description

Add capability to block a user by rate limiter.

## Pull request type

Please check the type of change your PR introduces:
- [ ] Feature

### Checklist

- [ ] Linter passes correctly
- [ ] Add tests which fail without the change (if possible)
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary

## Does this introduce a breaking change?

- [ ] No

## Further comments

The type change uint32->int32 shouldn't break clients with reasonable config.

### CODE REVIEW

**Comment by vfoucault** [comment]
Hello, I wonder why not simply removing the user would resolve your issue ? What is the target workflow for this ? 

Also, I would be more in favor to add a new field active / inactive, but still, why not simply remove the user from the configuration where anyhow you'll have to touch the configuration for this to be effective.

**Comment by tomershafir** [comment]
The goal is to temporarily block a user. I would find it better to mutate a config entry rather than rm it and later recover the removed user from git or other source. Though you can do an ugly comment. I guess its nice to have

**Comment by mga-chka** [comment]
Hi, can you add a test with a negative number, you can look at [this test](https://github.com/ContentSquare/chproxy/blob/master/proxy_test.go#L407) as inspiration?

**Comment by tomershafir** [comment]
@mga-chka done

**Review by mga-chka — APPROVED** [review]

**Pull request merged**
